// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW1iX9QycVHutFPwN1w7Da8fWcehkw8PQ',
    appId: '1:137569014332:web:e7f7c95e0b21e43d67e939',
    messagingSenderId: '137569014332',
    projectId: 'sterownik-akwarium',
    authDomain: 'sterownik-akwarium.firebaseapp.com',
    storageBucket: 'sterownik-akwarium.appspot.com',
    measurementId: 'G-0F0K23D2QS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBttYWvmsTcz93OhekgoHZfa46DwJp8Lzc',
    appId: '1:137569014332:android:b4c1f5a6c090fe4367e939',
    messagingSenderId: '137569014332',
    projectId: 'sterownik-akwarium',
    storageBucket: 'sterownik-akwarium.appspot.com',
    androidClientId: 'your-android-client-id',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT8U-y2ZYWECS6U0_6_GTd5J4xnR_lDF4',
    appId: '1:137569014332:ios:23604125ee8e799467e939',
    messagingSenderId: '137569014332',
    projectId: 'sterownik-akwarium',
    storageBucket: 'sterownik-akwarium.appspot.com',
    iosBundleId: 'com.example.sterownikAkwarium',
    iosClientId: 'your-ios-client-id',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT8U-y2ZYWECS6U0_6_GTd5J4xnR_lDF4',
    appId: '1:137569014332:ios:1fa87b43455fac7067e939',
    messagingSenderId: '137569014332',
    projectId: 'sterownik-akwarium',
    storageBucket: 'sterownik-akwarium.appspot.com',
    iosBundleId: 'com.example.sterownikAkwarium.RunnerTests',
  );
}
